apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ie41ptcbj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ie41ptcbj-nodejs 
  name: ie41ptcbj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ie41ptcbj-nodejs 
